// content/report.md: what a person should read before the content is imported.

const list = (rows, empty) => (rows.length ? rows.map(r => `- ${r}`).join('\n') : `_${empty}_`);

export function renderReport({ courses, lessonCount, checkpointCount, orphans, findings, specProblems }) {
  const items = courses.flatMap(c => c.units.flatMap(u => u.items));
  const byType = {};
  for (const item of items) {
    const key = [item.type, ...item.tags].join(' / ');
    byType[key] = (byType[key] || 0) + 1;
  }
  const drafts = courses.filter(c => c.status === 'draft').map(c => c.id);
  const vocabulary = findings.filter(f => f.kind === 'vocabulary');
  const unresolved = findings.filter(f => f.kind === 'unresolved-link');
  const missing = findings.filter(f => f.kind === 'missing-lesson');
  const emails = findings.filter(f => f.kind === 'email-replaced');

  return `# Content extraction report

Generated by \`npm run extract\`; do not edit by hand. Read it before the content is imported.

## Counts

- Courses: ${courses.length}${drafts.length ? ` (draft: ${drafts.join(', ')})` : ''}
- Lessons extracted: ${lessonCount}
- Checkpoints from lesson pages and notes: ${checkpointCount}
- Items: ${items.length}
${Object.entries(byType).sort().map(([k, n]) => `  - ${k}: ${n}`).join('\n')}

## Checkpoint spec problems

${list(specProblems.map(p => `\`${p}\``), 'None.')}

## Spec notes to review

Places where \`tools/extract/checkpoints.json\` departs from the audit or had to interpret the page.

${list(findings.filter(f => f.kind === 'spec-note').map(f => `\`${f.where}\`: ${f.detail}`), 'None.')}

## Email instructions replaced

Only the sentences asking for emailed work were swapped for "Submit your work with the form below."
Lines marked **flattened** had other formatting (bold, links) in the kept text; check it still reads well.

${list(emails.map(f => `\`${f.where}\`${f.flattened ? ' **flattened**' : ''}: "${f.before}" became "${f.after}"`), 'None.')}

## Lesson files no course reaches (not extracted)

${list(orphans.map(p => `\`${p}\``), 'None.')}

## Lessons a course links to that don't exist

${list(missing.map(f => `\`${f.where}\` links to \`${f.path}\``), 'None.')}

## Markup outside the lesson vocabulary

The importer's sanitiser drops these. Fix the source if any of it matters.

${list(vocabulary.map(f => `\`${f.where}\`: ${f.detail}`), 'None.')}

## Links that point at nothing the new site serves

${list(unresolved.map(f => `\`${f.where}\`: \`${f.url}\``), 'None.')}
`;
}
